[phases.setup]
nixPkgs = ["python311", "gcc", "postgresql"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install gunicorn",
    "cd vridge_back && pip install -r requirements.txt",
    "cd vridge_back && python manage.py collectstatic --noinput || true"
]

[phases.build]
cmds = [
    "cd vridge_back && python manage.py migrate --noinput || true"
]

[start]
cmd = "gunicorn railway_router:application --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120 --preload --log-level info"