[phases.setup]
nixPkgs = ["python311", "gcc", "postgresql"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install gunicorn dj-database-url psycopg2-binary",
    "pip install -r vridge_back/requirements.txt"
]

[phases.build]
cmds = [
    "python railway_migration.py",
    "python railway_collectstatic.py"
]

[start]
cmd = "gunicorn railway_wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --preload --log-level info"