[phases.setup]
nixPkgs = ["python39", "postgresql"]

[phases.install]
cmd = "pip install -r requirements.txt"

[start]
cmd = "gunicorn minimal_health_wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 30 --access-logfile - --error-logfile -"