[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn simple_health:application --bind 0.0.0.0:$PORT --workers 1 --timeout 120"