#!/bin/bash
# Railway 배포 명령어 모음

echo "=== Railway 배포 가이드 ==="
echo ""
echo "1. 헬스체크 문제 해결을 위한 Procfile 변경:"
echo "   현재 Procfile을 백업하고 새 Procfile 사용:"
echo ""
echo "   cp Procfile Procfile.backup"
echo "   cp Procfile.health Procfile"
echo ""
echo "2. Railway 환경 변수 설정 (Railway 대시보드에서):"
echo "   - PORT: (Railway가 자동 설정)"
echo "   - DATABASE_URL: (PostgreSQL URL)"
echo "   - SECRET_KEY: (보안 키)"
echo "   - DJANGO_SETTINGS_MODULE: config.settings.railway"
echo "   - RAILWAY_ENVIRONMENT: production"
echo ""
echo "3. 배포 커밋:"
echo "   git add -A"
echo "   git commit -m 'fix: Railway health check with minimal WSGI handler'"
echo "   git push"
echo ""
echo "4. Railway 헬스체크 설정 (대시보드):"
echo "   - Health Check Path: /api/health/"
echo "   - Health Check Timeout: 30s"
echo "   - Max Retries: 3"
echo ""
echo "5. 배포 후 확인:"
echo "   curl https://videoplanet.up.railway.app/api/health/"
echo ""
echo "=== 문제 해결 ==="
echo ""
echo "만약 여전히 500 에러가 발생한다면:"
echo "1. Railway 로그 확인: railway logs"
echo "2. 환경 변수 확인: railway variables"
echo "3. 데이터베이스 연결 확인"
echo ""