#!/bin/bash

echo "==========================================="
echo "🚨 Railway 헬스체크 긴급 복구"
echo "==========================================="
echo ""
echo "Railway 대시보드에서 실행:"
echo ""
echo "1. Settings → Deploy 탭"
echo "2. Start Command를 다음으로 변경:"
echo ""
echo "   python emergency_health_fix.py"
echo ""
echo "또는"
echo ""
echo "   gunicorn config.wsgi:application --bind 0.0.0.0:\$PORT --workers 1 --threads 1 --timeout 120 --log-level ERROR"
echo ""
echo "3. Variables 탭에서 추가:"
echo "   DJANGO_LOG_LEVEL=ERROR"
echo "   PYTHONUNBUFFERED=1"
echo "   DISABLE_COLLECTSTATIC=1"
echo ""
echo "4. Deploy 탭 → Restart"
echo ""
echo "==========================================="
echo "테스트:"
echo "curl https://videoplanet.up.railway.app/api/health/"
echo "==========================================="